### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by lmguzman** [valentinitnelav/bootstrapnet#1]
Hi Valentin, 

Tiffany sent me the link to your package and I look forward to see the bootstrapping you have done for the network metrics. 

Im having one problem with the installation. When I tried to install it its telling me that I need parallel 3.5 or higher = "namespace ‘parallel’ 3.5.1 is already loaded, but >= 3.6 is required".

I have R version 3.5.1 and I can't update just parallel because it is part of base R. I think you should allow parallel to have version 3.5 if you are allowing R to be version 3.5

Thanks!

Melissa

**Comment by valentinitnelav** [comment]
Hey Melissa ( @lmguzman )

Thanks for testing the package!
I listed older versions of the packages in the DESCRIPTION file and hopefully this fixes the issue. I didn't test though if things work correctly with older versions. I used actually R 3.6 and latest versions of the needed packages to build `bootstrapnet`. In case things fail, let me know, but the straightforward solution for now would be to update R and packages.

Best,
Valentin
